---
- name: Generate ansible-tower scheduled notification inventory based off of engagement.json
  hosts: tower-jobs-schedules
  gather_facts: false
  tasks:
    - name: "Fail If Working Directory Is Not Provided"
      fail:
        msg: "directory var needs to be provided in order to ensure a safe working directory"
      when:
        - directory is undefined or (directory | trim) == ""

    - name: Read Engagement Data
      include_vars:
        file: "{{ directory }}/engagement.json"

    - name: Residency Engagement Type inventory
      block:
        - name: "Write inventory to file"
          template:
            src: "tower-jobs-schedules.yaml.j2"
            dest: "{{ directory }}/iac/inventories/tower-jobs-schedules/inventory/group_vars/tower-jobs-schedules.yaml"

        - name: "Create hosts file"
          copy:
            src: "hosts"
            dest: "{{ directory }}/iac/inventories/tower-jobs-schedules/inventory/hosts"
      when: 
        - engagement_type == 'Residency'
