---
- name: Initialize Ansible Tower scheduled notification project, job template, inventory and schedules
  hosts: tower-jobs-init
  gather_facts: false

  vars:
    conf:
      tower_host: https://10.9.51.237
      tower_password: G5JbUCQpR4cYL7
      tower_username: admin
      validate_certs: no
    scm_credential_name: "gitlab-scm"
    customer_engagement: "initech-test_procedure_specification"
    organization: dev
    url: "ssh://git@gitlab.consulting.redhat.com:2222/rht-labs/scratch/lodestar-sandbox/initech/test-procedure-specification/iac.git"

  tasks:
    - name: "Create the {{ customer_engagement }}-project"
      tower_project:    
        name: "{{ customer_engagement }}-project"
        description: "Project for {{ customer_engagement }}"
        organization: "{{ organization }}"
        scm_type: "git"
        scm_url: "{{ url }}"
        scm_branch: "master"
        credential: "{{ scm_credential_name }}"
        scm_update_on_launch: true
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"
        state: present
      
    - name: Create an inventory for {{ customer_engagement }}
      tower_inventory:
        name: "{{ customer_engagement }}-inventory"
        description: "Inventory for {{ customer_engagement }}"
        organization: "{{ organization }}"
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"
        state: present

    - name: Add an inventory source
      tower_inventory_source:
        name: "{{ customer_engagement }}-inventory-source"
        description: Source for {{ customer_engagement }}-inventory
        inventory: "{{ customer_engagement }}-inventory"
        source: scm
        source_project: "{{ customer_engagement }}-project"
        credential: "{{ scm_credential_name }}"
        source_path: iac/inventories/tower-jobs-schedules/inventory
        update_on_launch: yes
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"
        state: present

    - name: Create job template
      tower_job_template:
        name: "configure-ansible-tower"
        job_type: "run"
        inventory: "empty-inventory-dev"
        project: "infra-ansible"
        playbook: "playbooks/ansible/tower/configure-ansible-tower.yml"
        ask_inventory_on_launch: yes
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"
        state: "present"

    - name: Launch a job with inventory and credential
      tower_job_launch:
        job_template: "configure-ansible-tower"
        inventory: "{{ customer_engagement }}-inventory"
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"
      register: job
    - name: Wait for job max 120s
      tower_job_wait:
        job_id: "{{ job.id }}"
        timeout: 120
        tower_host: "{{ conf.tower_host }}"
        tower_password: "{{ conf.tower_password }}"
        tower_username: "{{ conf.tower_username }}"
        validate_certs: "{{ conf.validate_certs }}"